const db = [
  { id: 1, word: "聞(기)取る", reading: "ききとる", meaning: "알아듣다, 청취하다", tag: "日常", exJa: "英語を聞き取る力", exKo: "영어를 알아듣는 능력" },
  { id: 2, word: "見つける", reading: "みつける", meaning: "찾(아내)다, 낯익다", tag: "日常", exJa: "-", exKo: "-" },
  { id: 3, word: "誠意", reading: "せいい", meaning: "성의", tag: "ビジネス", exJa: "-", exKo: "-" },
  { id: 4, word: "交互", reading: "こうご", meaning: "서로 번갈아 함", tag: "日常", exJa: "-", exKo: "-" },
  { id: 5, word: "腹黒", reading: "はらぐろ", meaning: "속이 검음, 음험함", tag: "スラング", exJa: "-", exKo: "-" },
  { id: 6, word: "相応しい", reading: "ふさわしい", meaning: "어울리다, 걸맞다", tag: "日常", exJa: "年齢に相応しい", exKo: "나이에 어울리다" },
  { id: 7, word: "定番", reading: "ていばん", meaning: "기본 아이템", tag: "ビジネス", exJa: "飽きのこない定番の服", exKo: "질리지 않는 기본형의 옷" },
  { id: 8, word: "口座振替", reading: "こうざふりかえ", meaning: "자동 계좌 이체", tag: "日常", exJa: "水道料金を口座から引き落とす", exKo: "수도 요금을 계좌에서 자동 이체하다" },
  { id: 9, word: "沼る", reading: "ぬまる", meaning: "깊이 빠져들다", tag: "スラング", exJa: "-", exKo: "-" },
  { id: 10, word: "丸投げ", reading: "まるなげ", meaning: "통째로 떠넘기다", tag: "ビジネス", exJa: "仕事を丸投げする", exKo: "일을 통째로 떠넘기다" },
  { id: 11, word: "手取り", reading: "てどり", meaning: "실수령액", tag: "ビジネス", exJa: "手取りで20万円もらう", exKo: "실수령액으로 20만 엔을 받다" },
  { id: 12, word: "逆張り", reading: "ぎゃくば리", meaning: "대세를 거스름", tag: "ビジネス", exJa: "-", exKo: "-" },
  { id: 13, word: "どんぴしゃ", reading: "どんぴしゃ", meaning: "딱 들어맞음", tag: "スラング", exJa: "好みにどんぴしゃだよ", exKo: "취향에 딱이야" },
  { id: 14, word: "頭に来る", reading: "あたまにくる", meaning: "화가 나다", tag: "日常", exJa: "-", exKo: "-" },
  { id: 15, word: "守秘", reading: "しゅひ", meaning: "비밀 유지", tag: "ビジネス", exJa: "守秘義務を守る", exKo: "비밀 유지 의무를 지키다" },
  { id: 16, word: "捗る", reading: "はかどる", meaning: "진척되다", tag: "ビジネス", exJa: "仕事が捗る", exKo: "업무가 잘 진척되다" },
  { id: 17, word: "焦る", reading: "あせる", meaning: "초조해하다", tag: "日常", exJa: "-", exKo: "-" },
  { id: 18, word: "練る", reading: "ねる", meaning: "다듬다, 짜다", tag: "ビジネス", exJa: "作戦を練る", exKo: "작전을 짜다" },
  { id: 19, word: "承る", reading: "うけたまわる", meaning: "받들다, 듣다", tag: "ビジネス", exJa: "-", exKo: "-" },
  { id: 20, word: "踏襲", reading: "とうしゅう", meaning: "답습", tag: "ビジネス", exJa: "前例を踏襲する", exKo: "전례를 답습하다" }
];
